# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.24.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v -o kerio-mirror-go${{ matrix.os == 'windows-latest' && '.exe' || '' }} ./cmd/server

    - name: Test
      run: go test -v -coverprofile=coverage ./...

    - name: Upload coverage
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage
        flags: unittests
        fail_ci_if_error: false

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: kerio-mirror-go-${{ matrix.os }}
        path: kerio-mirror-go${{ matrix.os == 'windows-latest' && '.exe' || '' }}
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/kerio-mirror-go-ubuntu-latest/kerio-mirror-go
          artifacts/kerio-mirror-go-windows-latest/kerio-mirror-go.exe
          artifacts/kerio-mirror-go-macos-latest/kerio-mirror-go
        generate_release_notes: true
        draft: false
        prerelease: false
