# Улучшенный workflow для Go-проекта
# - Добавлены проверки на форматирование и статический анализ
# - Кэширование зависимостей вынесено отдельно для ускорения сборки
# - Использование matrix для go-version (расширяемость)
# - Артефакты собираются только для релизов — лишние шаги убраны из билда
# - Добавлены комментарии для ясности

name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.24.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go-version }}-

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Check formatting
      run: go fmt ./...

    - name: Static analysis
      run: go vet ./...

    - name: Build
      run: go build -v -o kerio-mirror-go${{ matrix.os == 'windows-latest' && '.exe' || '' }} ./cmd/server

    - name: Test
      run: go test -v -coverprofile=coverage.out ./...

    - name: Upload coverage
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.out
        flags: unittests
        fail_ci_if_error: false

    # Артефакты собираются только при релизе (release job)

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download binaries (Ubuntu)
      uses: actions/download-artifact@v4
      with:
        name: kerio-mirror-go-ubuntu-latest
        path: ./artifacts

    - name: Download binaries (Windows)
      uses: actions/download-artifact@v4
      with:
        name: kerio-mirror-go-windows-latest
        path: ./artifacts

    - name: Download binaries (macOS)
      uses: actions/download-artifact@v4
      with:
        name: kerio-mirror-go-macos-latest
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/kerio-mirror-go-ubuntu-latest/kerio-mirror-go
          artifacts/kerio-mirror-go-windows-latest/kerio-mirror-go.exe
          artifacts/kerio-mirror-go-macos-latest/kerio-mirror-go
        generate_release_notes: true
        draft: false
        prerelease: false