# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.24.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v -o kerio-mirror-go${{ matrix.os == 'windows-latest' && '.exe' || '' }} ./cmd/server

    - name: Test
      run: go test -v -race -coverprofile=coverage.txt ./...

    - name: Upload coverage
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v4
      with:
        files: ./coverage.txt
        flags: unittests
        fail_ci_if_error: false

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: kerio-mirror-go-${{ matrix.os }}
        path: kerio-mirror-go${{ matrix.os == 'windows-latest' && '.exe' || '' }}
